baseURL = ""
languageCode = "en-us"
timeZone = "UTC"
title = "Kubewarden"
theme = "projects-theme"
pluralizeListTitles = false
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableGitInfo = true
googleAnalytics = 'G-PSW07XK7TM'

[blackfriday]
fractions = false
#hrefTargetBlank = true

[outputFormats.Algolia]
baseName = "algolia"
isPlaintext = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[params]
github = "https://github.com/kubewarden"

[outputs]
home = ["HTML", "RSS"]

[privacy]
[privacy.googleAnalytics]
anonymizeIP = true

[menu]

[[menu.main]]
identifier = "platform"
name = "Platform"
url = "/#components"
weight = -140

[[menu.main]]
identifier = "docs"
name = "Docs"
url = "https://docs.kubewarden.io/"
weight = -130

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = -110

[[menu.main]]
identifier = "community"
name = "Community"
url = "/#get-in-touch"
weight = -100

[[menu.main]]
identifier = "meetings"
name = "Community meetings"
parent = "community"
url = "/#get-in-touch"
weight = -99

[[menu.main]]
identifier = "slack"
name = "Slack"
parent = "community"
url = "https://kubernetes.slack.com/?redir=%2Fmessages%2Fkubewarden"
weight = -97

[[menu.main]]
identifier = "bluesky"
name = "Bluesky"
parent = "community"
url = "https://bsky.app/profile/kubewarden.io"
weight = -96

[[menu.main]]
identifier = "mastodon"
name = "Mastodon"
parent = "community"
url = "https://hachyderm.io/@kubewarden"
weight = -95
[menu.main.params]
rel = 'me'

[[menu.main]]
identifier = "enterprise"
name = "Enterprise"
url = "https://docs.kubewarden.io/enterprise"
weight = -50

[taxonomies]
component = "components"
type = "types"
