name: Publish Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Temporal workaround for innacessible mirrors
        run: |
          sudo sed -i 's|mirror+file:/etc/apt/apt-mirrors.txt|http://archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list
          sudo apt-get update
      - name: Install hugo
        run: |
          sudo apt install hugo
          hugo version
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b #v5.0.0
      - name: Build Site
        run: |
          set -e

          hugo --gc --minify --cleanDestinationDir \
            -d ${{ runner.temp }}/gh-pages/
      - name: Upload gh-pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ${{ runner.temp }}/gh-pages/

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Publish Site
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e #v4.0.5
