---
name: "Updatecli: Dependency Management"

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 3 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Updatecli Binary
        uses: updatecli/updatecli-action@d422ba543720d01a96d4c3e3ab8544cc188cd711 # v3.5.0

      - name: Run Updatecli in enforce mode
        run: "updatecli compose apply"
        env:
          GITHUB_ACTOR: "${{ github.actor }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
